=== raksha46kmt/Event-Management/search.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="search">
    <xs:restriction base="xs:string">
      <xs:length value="15"/>
    </xs:restriction>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Search" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="From"/>
              <xs:element type="xs:string" name="To"/>
              <xs:element type="xs:integer" name="Date"/>
              <xs:element type="xs:integer" name="Time"/>
              <xs:element type="xs:string" name="Place"/>
              <xs:element type="xs:string" name="Flightname"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== raksha46kmt/Event-Management/search.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="search.xsl"?>
<Search xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="search.xsd">
  <search>
  <From>Delhi</From>
  <To>kanyakumari</To>
  <Date>1-10-2020</Date>
  <Time>10.00am</Time>
  <Place>Gandhi international airport</Place>
  <Flightname>kingfisher</Flightname>
</search>
<search>
  <From>kolkata</From>
  <To>Malaysia</To>
  <Date>2-10-2020</Date>
  <Time>11.00am</Time>
  <Place>Nehru international airport</Place>
  <Flightname>Quatar Airways</Flightname>
</search>
<search>
  <From>London</From>
  <To>Mumbai</To>
  <Date>5-10-2020</Date>
  <Time>09.00am</Time>
  <Place>Sri Guru International Airport</Place>
  <Flightname>Cathay Pacific Airway</Flightname>
</search>
<search>
  <From>Dubai</From>
  <To>Singapore</To>
  <Date>8-10-2020</Date>
  <Time>10.30am</Time>
  <Place>Dubai International Airport</Place>
  <Flightname>Singapore Airlines</Flightname>
</search>
<search>
  <From>Chennai</From>
  <To>Canada</To>
  <Date>10-10-2020</Date>
  <Time>02.00pm</Time>
  <Place>Anna international Airport</Place>
  <Flightname>ANA All Nippon Airways</Flightname>
</search>
<search>
  <From>Delhi</From>
  <To>Frances</To>
  <Date>12-10-2020</Date>
  <Time>08.00am</Time>
  <Place>Indira Gandhi international airport</Place>
  <Flightname>Quantas Airway</Flightname>
</search>
</Search>
